version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      playwright:
        patterns:
          - '@playwright/*'
          - 'allure-*'
      linting:
        patterns:
          - 'eslint*'
          - 'typescript-eslint'
          - 'prettier'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
